# Day 35 — PyTorch Foundations & Tensor Operations

## Topics Covered
- Introduction to PyTorch
- What are Tensors?
- Tensor Creation
- Tensor Operations
- Tensor Indexing & Slicing
- Tensor Reshaping
- Broadcasting
- NumPy vs PyTorch
- GPU & CUDA Basics
- Automatic Differentiation (Autograd)
- Practical Hands-on Exercises
- Mini Tensor Projects

---

# Learning Goal

By the end of this notebook, you will be able to:

✅ Understand PyTorch fundamentals  
✅ Create and manipulate tensors  
✅ Perform mathematical tensor operations  
✅ Understand tensor dimensions and shapes  
✅ Use GPU acceleration  
✅ Understand automatic differentiation  
✅ Build the foundation required for Deep Learning


# 1. Introduction to PyTorch

## What is PyTorch?

PyTorch is an open-source Deep Learning framework developed by Meta (Facebook).

It is widely used for:
- Deep Learning
- Computer Vision
- NLP
- Generative AI
- Research & Production AI systems

---

## Why PyTorch is Popular

### 1. Easy to Learn
PyTorch syntax feels very similar to Python and NumPy.

### 2. Dynamic Computation Graph
Graphs are built dynamically during execution.

### 3. GPU Support
PyTorch can run tensor operations on GPUs.

### 4. Strong Community
Used by researchers and companies globally.

---

## PyTorch Ecosystem

| Library | Purpose |
|---|---|
| torch | Core tensor library |
| torchvision | Computer vision |
| torchaudio | Audio processing |
| torchtext | NLP |


# 2. Installing PyTorch

## Install PyTorch

```bash
pip install torch torchvision torchaudio
```

---

## Verify Installation


# 3. Importing PyTorch

```python
import torch

print(torch.__version__)
```

---

## Checking GPU Availability


# 4. Understanding Tensors

## What is a Tensor?

A tensor is a multi-dimensional data structure used in Deep Learning.

### Tensor Hierarchy

| Type | Dimensions |
|---|---|
| Scalar | 0D |
| Vector | 1D |
| Matrix | 2D |
| Tensor | 3D+ |

---

## Why Tensors Matter

Everything in Deep Learning becomes tensors:
- Images
- Text
- Audio
- Model Weights
- Predictions


# 5. Tensor Creation

## Tensor Creation Methods

PyTorch provides multiple ways to create tensors.

### Common Methods
- torch.tensor()
- torch.zeros()
- torch.ones()
- torch.rand()
- torch.randn()
- torch.arange()
- torch.linspace()


# 6. Tensor Shapes and Dimensions

## Tensor Shape

Shape represents:
- number of rows
- columns
- dimensions

Example:
```python
tensor.shape
```

---

## Tensor Dimensions

| Tensor | Shape |
|---|---|
| Scalar | [] |
| Vector | [3] |
| Matrix | [2,3] |


# 7. Tensor Operations

## Arithmetic Operations

Tensors support:
- Addition
- Subtraction
- Multiplication
- Division

---

## Matrix Multiplication

Important in Deep Learning.

---

## Statistical Operations
- Mean
- Sum
- Max
- Min


# 8. Tensor Indexing & Slicing

## Indexing

Access specific elements from tensors.

### Examples
- First row
- Specific column
- Conditional selection


# 9. Tensor Reshaping

## Reshaping Tensors

Important for:
- Neural Networks
- Image Processing
- Batch Operations

### Functions
- reshape()
- view()
- unsqueeze()
- squeeze()


# 10. Broadcasting

## Broadcasting

Broadcasting allows operations between tensors of different shapes.

This makes tensor operations efficient and powerful.


# 11. NumPy vs PyTorch

## Similarities
- Multi-dimensional arrays
- Mathematical operations
- Fast computation

---

## Differences

| NumPy | PyTorch |
|---|---|
| CPU focused | GPU support |
| No autograd | Automatic differentiation |
| Scientific computing | Deep learning |


# 12. GPU & CUDA

## GPU Acceleration

Deep learning becomes much faster using GPUs.

---

## CUDA

CUDA allows PyTorch tensors to run on NVIDIA GPUs.


# 13. Autograd

# Automatic Differentiation (Autograd)

Autograd is one of PyTorch’s most powerful features.

It automatically calculates gradients for Deep Learning.

---

## Why Gradients Matter

Gradients help neural networks learn by updating weights.

---

## Key Concepts
- requires_grad
- backward()
- computational graph


# 14. Mini Hands-On Projects

# Mini Projects

## Project 1
Tensor Calculator

## Project 2
Matrix Multiplication Demo

## Project 3
Gradient Calculation Example


# 15. Summary

# Day 35 Summary

Today you learned:
- PyTorch basics
- Tensor fundamentals
- Tensor operations
- GPU support
- Autograd basics

You now have the foundation required for:
- Neural Networks
- Training Loops
- Optimizers
- Deep Learning Models


In [1]:
!pip uninstall torch torchvision torchaudio -y

Found existing installation: torch 2.12.0
Uninstalling torch-2.12.0:
  Successfully uninstalled torch-2.12.0
Found existing installation: torchvision 0.27.0
Uninstalling torchvision-0.27.0:
  Successfully uninstalled torchvision-0.27.0
Found existing installation: torchaudio 2.11.0
Uninstalling torchaudio-2.11.0:
  Successfully uninstalled torchaudio-2.11.0


In [1]:
!pip cache purge

Files removed: 18 (127.8 MB)


In [2]:
!pip install torch torchvision torchaudio

Defaulting to user installation because normal site-packages is not writeable


In [1]:
# Import PyTorch
import os
os.environ["CUDA_VISIBLE_DEVICES"] = ""
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"
import torch

#import torch

print("PyTorch Version:", torch.__version__)

PyTorch Version: 2.12.0+cpu


In [2]:
# Check GPU availability
print("CUDA Available:", torch.cuda.is_available())

CUDA Available: False


In [3]:

# This sets 'cpu' as your default device since CUDA is not present
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Example: Creating a tensor and sending it to your available device
x = torch.rand(3, 3).to(device)
print(x)

Using device: cpu
tensor([[0.8479, 0.0341, 0.8879],
        [0.1995, 0.9213, 0.2290],
        [0.6387, 0.9855, 0.8949]])


In [4]:
# Scalar Tensor
scalar = torch.tensor(5)
print(scalar)

# 1D Tensor
vector = torch.tensor([1,2,3])
print(vector)

# 2D Tensor
matrix = torch.tensor([[1,2],[3,4]])
print(matrix)

# 3D Tensor
matrix = torch.tensor([[[1,2],[3,4]],[[10,2],[30,4]]])
print(matrix)

print("Shape:", matrix.shape)
print("Datatype:", matrix.dtype)
print("Dimensions:", matrix.ndim)

tensor(5)
tensor([1, 2, 3])
tensor([[1, 2],
        [3, 4]])
tensor([[[ 1,  2],
         [ 3,  4]],

        [[10,  2],
         [30,  4]]])
Shape: torch.Size([2, 2, 2])
Datatype: torch.int64
Dimensions: 3


In [5]:
# Creating tensors

zeros = torch.zeros((2,3))
ones = torch.ones((2,3))
random_tensor = torch.rand((2,3))

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Random Tensor:\n", random_tensor)

Zeros:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Ones:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Random Tensor:
 tensor([[0.0533, 0.5447, 0.8051],
        [0.0227, 0.0833, 0.2001]])


In [6]:
# Tensor shape and datatype

x = torch.tensor([[1,2,3],[4,5,6]])

print("Shape:", x.shape)
print("Datatype:", x.dtype)
print("Dimensions:", x.ndim)

Shape: torch.Size([2, 3])
Datatype: torch.int64
Dimensions: 2


In [7]:
# Arithmetic operations

a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

print("Addition:", a+b)
print("Subtraction:", a-b)
print("Multiplication:", a*b)
print("Division:", a/b)

Addition: tensor([5, 7, 9])
Subtraction: tensor([-3, -3, -3])
Multiplication: tensor([ 4, 10, 18])
Division: tensor([0.2500, 0.4000, 0.5000])


In [8]:
# Matrix multiplication

matrix1 = torch.tensor([[1,2],[3,4]])
matrix2 = torch.tensor([[5,6],[7,8]])

result = torch.matmul(matrix1, matrix2)

print(result)

tensor([[19, 22],
        [43, 50]])


In [9]:
# Statistical operations

x = torch.tensor([1,2,3,4,5], dtype=torch.float32)

print("Mean:", torch.mean(x))
print("Sum:", torch.sum(x))
print("Max:", torch.max(x))
print("Min:", torch.min(x))

Mean: tensor(3.)
Sum: tensor(15.)
Max: tensor(5.)
Min: tensor(1.)


In [10]:
# Indexing and slicing

x = torch.tensor([[1,2,3],[4,5,6]])

print("First Row:", x[0])
print("Second Column:", x[:,1])

First Row: tensor([1, 2, 3])
Second Column: tensor([2, 5])


In [11]:
# Conditional selection

x = torch.tensor([1,2,3,4,5,6])

print(x[x > 3])

tensor([4, 5, 6])


In [12]:
# Reshaping tensors

x = torch.arange(12)

reshaped = x.reshape(3,4)

print(reshaped)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [13]:
# Unsqueeze and squeeze

x = torch.tensor([1,2,3])

print("Original Shape:", x.shape)

x_unsqueezed = x.unsqueeze(0)

print("After Unsqueeze:", x_unsqueezed.shape)

x_squeezed = x_unsqueezed.squeeze()

print("After Squeeze:", x_squeezed.shape)

Original Shape: torch.Size([3])
After Unsqueeze: torch.Size([1, 3])
After Squeeze: torch.Size([3])


In [14]:
# Broadcasting example

a = torch.tensor([[1],[2],[3]])
b = torch.tensor([10,20,30])

print(a + b)

tensor([[11, 21, 31],
        [12, 22, 32],
        [13, 23, 33]])


In [15]:
# NumPy to Tensor

import numpy as np

arr = np.array([1,2,3])

tensor = torch.from_numpy(arr)

print(tensor)

tensor([1, 2, 3])


In [16]:
# Tensor to NumPy

tensor = torch.tensor([4,5,6])

array = tensor.numpy()


print(array)

[4 5 6]


In [17]:
# Moving tensor to GPU

device = "cuda" if torch.cuda.is_available() else "cpu"

x = torch.tensor([1,2,3]).to(device)

print(x)
print("Device:", x.device)

tensor([1, 2, 3])
Device: cpu


In [18]:
# Autograd example

x = torch.tensor(2.0, requires_grad=True)

y = x**2

y.backward()

print(x)

print("Gradient:", x.grad)

tensor(2., requires_grad=True)
Gradient: tensor(4.)


In [19]:
# More autograd operations

x = torch.tensor(3.0, requires_grad=True)

y = 3*x**2 + 2*x + 1

y.backward()

print("dy/dx =", x.grad)

dy/dx = tensor(20.)


In [20]:
# Mini Tensor Calculator

a = torch.tensor(10.0)
b = torch.tensor(5.0)

print("Addition:", a+b)
print("Subtraction:", a-b)
print("Multiplication:", a*b)
print("Division:", a/b)

Addition: tensor(15.)
Subtraction: tensor(5.)
Multiplication: tensor(50.)
Division: tensor(2.)


In [21]:
# Practice Exercise

# Create a random tensor of shape (3,3)
# Find its mean
# Reshape it into (1,9)

x = torch.rand((3,3))

print("Tensor:\n", x)

print("Mean:", torch.mean(x))

reshaped = x.reshape(1,9)

print("Reshaped Tensor:\n", reshaped)

Tensor:
 tensor([[0.2630, 0.4980, 0.5693],
        [0.2995, 0.1454, 0.6091],
        [0.0454, 0.5450, 0.6801]])
Mean: tensor(0.4061)
Reshaped Tensor:
 tensor([[0.2630, 0.4980, 0.5693, 0.2995, 0.1454, 0.6091, 0.0454, 0.5450, 0.6801]])
