
# 🚀 Day 44: Encoder Inside Transformers (Part 1)

## Topics Covered
1. Word Embedding
2. Positional Encoding
3. Self-Attention
4. Residual Connection & Layer Normalization

**Learning Style:** Theory Heavy + Hands-On + Mini Project



# Learning Objectives

By the end of this notebook, you will be able to:

- Explain the four major steps inside a Transformer Encoder.
- Understand why embeddings and positional encoding are necessary.
- Calculate Self-Attention step-by-step.
- Understand residual connections intuitively.
- Build a mini encoder pipeline using Python.


# Word Embedding

## Theory

Transformers cannot process text directly.

Words are converted into dense vectors called embeddings.

### Why Embeddings?

- Neural networks understand numbers.
- Similar words have similar vectors.
- Capture semantic relationships.

Example:
King − Man + Woman ≈ Queen


## Hands-On Exercise

In [1]:

words = ["I", "love", "AI"]
embeddings = {
    "I": [0.12, -0.45, 0.87],
    "love": [0.31, 0.92, -0.11],
    "AI": [-0.76, 0.23, 0.45]
}

for word in words:
    print(word, "→", embeddings[word])


I → [0.12, -0.45, 0.87]
love → [0.31, 0.92, -0.11]
AI → [-0.76, 0.23, 0.45]


# Positional Encoding

## Theory

Transformers process all words simultaneously.

Without positional encoding:

Dog bites man
Man bites dog

would appear identical.

### Original Formula

PE(pos,2i)=sin(...)
PE(pos,2i+1)=cos(...)


## Hands-On Exercise

In [2]:

import numpy as np

def positional_encoding(position, d_model):
    pe = np.zeros((position, d_model))

    for pos in range(position):
        for i in range(0, d_model, 2):
            pe[pos, i] = np.sin(pos / (10000 ** (i / d_model)))
            if i + 1 < d_model:
                pe[pos, i+1] = np.cos(pos / (10000 ** (i / d_model)))

    return pe

pe = positional_encoding(5, 6)
print(pe)


[[ 0.          1.          0.          1.          0.          1.        ]
 [ 0.84147098  0.54030231  0.04639922  0.99892298  0.00215443  0.99999768]
 [ 0.90929743 -0.41614684  0.0926985   0.99569422  0.00430886  0.99999072]
 [ 0.14112001 -0.9899925   0.1387981   0.9903207   0.00646326  0.99997911]
 [-0.7568025  -0.65364362  0.18459872  0.98281398  0.00861763  0.99996287]]


# Self-Attention

## Theory

Self-Attention asks:

Which words should I focus on?

### QKV

- Query: What am I looking for?
- Key: What do I contain?
- Value: What information should I provide?

### Formula

Attention(Q,K,V)
= softmax(QKᵀ/√dk)V


## Hands-On Exercise

In [3]:

import numpy as np

Q = np.array([[1,0,1]])
K = np.array([[1,1,0],[0,1,1]])
V = np.array([[1,2],[3,4]])

scores = Q @ K.T
weights = np.exp(scores) / np.sum(np.exp(scores))

output = weights @ V

print("Scores:", scores)
print("Weights:", weights)
print("Attention Output:", output)


Scores: [[1 1]]
Weights: [[0.5 0.5]]
Attention Output: [[2. 3.]]


# Residual Connection

## Theory

Deep networks may forget earlier information.

Residual Connection:

Output = Input + Sublayer(Input)

Benefits:
- Better gradient flow
- Stable training
- Preserves original information


## Hands-On Exercise

In [4]:

import numpy as np

x = np.array([1,2,3])
attention_output = np.array([0.5,0.2,0.8])

residual = x + attention_output

print("Input:", x)
print("Attention:", attention_output)
print("Residual Output:", residual)


Input: [1 2 3]
Attention: [0.5 0.2 0.8]
Residual Output: [1.5 2.2 3.8]



# Mini Project

Build a simplified Transformer Encoder pipeline:

Input Sentence
↓
Embedding
↓
Positional Encoding
↓
Self-Attention
↓
Residual Connection

Observe how information changes at each stage.


In [5]:

sentence = ["I", "love", "AI"]

print("Input:", sentence)

print("\nPipeline:")
for step in [
    "Embedding",
    "Positional Encoding",
    "Self-Attention",
    "Residual Connection"
]:
    print("↓", step)

print("\nFinal Encoder Representation Generated")


Input: ['I', 'love', 'AI']

Pipeline:
↓ Embedding
↓ Positional Encoding
↓ Self-Attention
↓ Residual Connection

Final Encoder Representation Generated



# Interview Questions

1. Why are embeddings necessary?
2. Why can't Transformers rely only on embeddings?
3. Explain Q, K, and V.
4. What problem do residual connections solve?
5. Why is self-attention better than RNNs for long dependencies?



# Day 44 Key Takeaway

Embeddings tell Transformers what words mean.

Positional Encoding tells them where words occur.

Self-Attention determines what matters.

Residual Connections ensure nothing important is lost.

Together, these form the foundation of modern Transformer encoders.
