
# 🚀 Day 42 — GRU (Gated Recurrent Unit)

# Deep Theory + Hands-On Master Notebook

## 📚 What You Will Learn

### Core Theory
- Introduction to GRU
- Why GRU was introduced
- Vanishing Gradient Problem
- Long-Term Dependency Problem
- GRU Architecture
- Update Gate
- Reset Gate
- Candidate Hidden State
- Hidden State Update Mechanism
- Forward Propagation
- Backpropagation Through Time (BPTT)
- Sequence Processing

---

### Advanced Theory
- GRU vs RNN vs LSTM
- Bidirectional GRU (BiGRU)
- Stacked / Deep GRU
- Stateful vs Stateless GRU
- Hyperparameters
- Sequence Padding & Masking
- Embedding + GRU Workflow

---

### Real-World Applications
- NLP
- Sentiment Analysis
- Chatbots
- Speech Recognition
- Time-Series Forecasting
- Sequence Prediction

---

### Hands-On Projects
✅ TensorFlow GRU  
✅ PyTorch GRU  
✅ Sentiment Classification  
✅ Time-Series Forecasting  
✅ Bidirectional GRU  
✅ Stacked GRU  

---

# 🎯 Learning Goal

By the end of this notebook, you will understand:

- How GRU works internally
- Why gates are important
- How GRU solves RNN limitations
- When to use GRU instead of LSTM
- How to build practical GRU applications



# 🧠 Introduction to GRU

GRU (Gated Recurrent Unit) is a type of Recurrent Neural Network (RNN) architecture designed for sequence learning.

It was introduced to solve major problems in traditional RNNs:

❌ Vanishing Gradients  
❌ Forgetting long-term information  
❌ Slow and unstable training  

---

# 🔥 Why GRU Became Popular

GRU introduced:

✅ Better memory handling  
✅ Faster training  
✅ Fewer parameters  
✅ Better gradient flow  
✅ Simpler architecture than LSTM  

---

# 🏗️ GRU Core Idea

Instead of blindly updating memory at every timestep, GRU intelligently decides:

- What to remember
- What to forget
- What to update

using gates.



# ⚠️ Problems with Traditional RNN

## 1️⃣ Vanishing Gradient Problem

During backpropagation:

\[
0.5 \times 0.5 \times 0.5 \times 0.5 \rightarrow 0
\]

Gradients become extremely small.

Result:
- Early layers stop learning
- Long-term memory disappears

---

## 2️⃣ Long-Term Dependency Problem

Example:

> "I was born in France ... I speak fluent French."

Traditional RNN may forget the earlier word "France".

GRU solves this using gated memory control.

---

# 🔄 Difference Between RNN, LSTM, and GRU

| Feature | RNN | LSTM | GRU |
|---|---|---|---|
| Gates | None | 3 | 2 |
| Cell State | No | Yes | No |
| Long-Term Memory | Weak | Strong | Strong |
| Parameters | Low | High | Medium |
| Speed | Fast | Slow | Faster |
| Complexity | Simple | Complex | Simpler |



# 🏛️ GRU Architecture Overview

GRU contains:

✅ Hidden State  
✅ Update Gate  
✅ Reset Gate  
✅ Candidate Hidden State  

---

# 🔐 Update Gate

Controls:

> How much previous memory should be retained?

Equation:

\[
z_t = \sigma(W_z[h_{t-1}, x_t])
\]

If:
- \(z_t \approx 1\) → keep old memory
- \(z_t \approx 0\) → update memory

---

# 🔓 Reset Gate

Controls:

> How much old information should be forgotten?

Equation:

\[
r_t = \sigma(W_r[h_{t-1}, x_t])
\]

---

# 🧪 Candidate Hidden State

Temporary new memory content.

\[
\tilde{h}_t = tanh(W[r_t * h_{t-1}, x_t])
\]

---

# 🧠 Final Hidden State

\[
h_t = (1-z_t)h_{t-1} + z_t\tilde{h}_t
\]



# 🔄 GRU Information Flow

Input → Gates → Candidate Memory → Hidden State Update → Output

The gates dynamically regulate:

✅ Information preservation  
✅ Memory updates  
✅ Forgetting irrelevant context  

---

# 📌 Why GRU Is Efficient

Unlike LSTM:
- No separate cell state
- Fewer gates
- Fewer parameters

Result:
✅ Faster training  
✅ Lower GPU memory usage  
✅ Better computational efficiency  


In [1]:

# 📦 Import Libraries

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import GRU, Dense, Dropout
from tensorflow.keras.optimizers import Adam



# 🛠️ Hands-On Project 1 — Basic GRU Classification

Goal:
Build a simple GRU-based binary classification model.

Dataset:
Synthetic sequence dataset.


In [2]:

# Create Dummy Sequential Data

X = np.random.rand(2000, 30, 8)

y = np.random.randint(0, 2, size=(2000, 1))

print("X Shape:", X.shape)
print("y Shape:", y.shape)


X Shape: (2000, 30, 8)
y Shape: (2000, 1)


In [3]:

# Build GRU Model

model = Sequential([
    
    GRU(
        units=64,
        input_shape=(30, 8),
        return_sequences=False
    ),
    
    Dropout(0.3),
    
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer=Adam(0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()


C:\ProgramData\anaconda3\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ gru (GRU)                            │ (None, 64)                  │          14,208 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 64)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 1)                   │              65 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 14,273 (55.75 KB)

 Trainable params: 14,273 (55.75 KB)

 Non-trainable params: 0 (0.00 B)

In [4]:

# Train Model

history = model.fit(
    X,
    y,
    epochs=5,
    batch_size=32,
    validation_split=0.2
)


Epoch 1/5
50/50 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - accuracy: 0.5056 - loss: 0.6991 - val_accuracy: 0.5150 - val_loss: 0.6935
Epoch 2/5
50/50 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.5138 - loss: 0.6941 - val_accuracy: 0.5225 - val_loss: 0.6926
Epoch 3/5
50/50 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.5106 - loss: 0.6937 - val_accuracy: 0.5175 - val_loss: 0.6929
Epoch 4/5
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5025 - loss: 0.6948 - val_accuracy: 0.5075 - val_loss: 0.6931
Epoch 5/5
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5075 - loss: 0.6932 - val_accuracy: 0.4950 - val_loss: 0.6932



# 📊 Understanding Important GRU Hyperparameters

| Hyperparameter | Meaning |
|---|---|
| units | Hidden neurons |
| return_sequences | Return full sequence or last output |
| dropout | Prevent overfitting |
| batch_size | Samples per training step |
| epochs | Full dataset iterations |
| learning_rate | Optimization step size |

---

# 💡 Practical Insight

Increasing hidden units:
✅ Better learning capacity  
❌ Higher computation cost  



# 🧠 Embedding + GRU Workflow

Typical NLP Pipeline:

Text → Tokenization → Embedding → GRU → Dense Layer → Prediction

Embedding converts words into dense vectors.


In [5]:

# Embedding + GRU Example

from tensorflow.keras.layers import Embedding

vocab_size = 10000

model = Sequential([
    
    Embedding(
        input_dim=vocab_size,
        output_dim=64
    ),
    
    GRU(128),
    
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ gru_1 (GRU)                          │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)


# 🤖 GRU for Sentiment Analysis

Applications:
- Movie review classification
- Customer feedback analysis
- Social media sentiment mining

Input:
Sequence of words

Output:
Positive / Negative / Neutral


In [6]:

# Sentiment Classification Example

from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer

texts = [
    "movie was amazing",
    "bad acting and poor story",
    "excellent performance",
    "terrible film"
]

labels = [1, 0, 1, 0]

tokenizer = Tokenizer(num_words=1000)

tokenizer.fit_on_texts(texts)

sequences = tokenizer.texts_to_sequences(texts)

X = pad_sequences(sequences, maxlen=5)

y = np.array(labels)

print(X)


[[ 0  0  1  2  3]
 [ 4  5  6  7  8]
 [ 0  0  0  9 10]
 [ 0  0  0 11 12]]



# ⏳ Hands-On Project 2 — Time-Series Forecasting

Goal:
Use GRU for sequence prediction.

Applications:
- Stock prices
- Weather forecasting
- Demand forecasting
- Sensor prediction


In [7]:

# Create Time-Series Data

data = np.sin(np.linspace(0, 100, 3000))

sequence_length = 30

X = []
y = []

for i in range(len(data) - sequence_length):

    X.append(data[i:i+sequence_length])
    y.append(data[i+sequence_length])

X = np.array(X)
y = np.array(y)

X = X.reshape(X.shape[0], X.shape[1], 1)

print(X.shape)
print(y.shape)


(2970, 30, 1)
(2970,)


In [8]:

# GRU Time-Series Model

model = Sequential([
    
    GRU(
        64,
        input_shape=(sequence_length, 1)
    ),
    
    Dense(1)
])

model.compile(
    optimizer='adam',
    loss='mse'
)

model.summary()


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ gru_2 (GRU)                          │ (None, 64)                  │          12,864 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │              65 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 12,929 (50.50 KB)

 Trainable params: 12,929 (50.50 KB)

 Non-trainable params: 0 (0.00 B)

In [9]:

# Train Time-Series GRU

history = model.fit(
    X,
    y,
    epochs=5,
    batch_size=32
)


Epoch 1/5
93/93 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 0.0423
Epoch 2/5
93/93 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0036
Epoch 3/5
93/93 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0017
Epoch 4/5
93/93 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 1.3501e-04
Epoch 5/5
93/93 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 3.8789e-06



# 🔄 Bidirectional GRU (BiGRU)

BiGRU processes sequences:
➡️ Forward  
⬅️ Backward  

Benefits:
✅ Better contextual understanding  
✅ Uses future + past context  

Commonly used in:
- NLP
- Translation
- Speech recognition


In [10]:

# Bidirectional GRU Example

from tensorflow.keras.layers import Bidirectional

model = Sequential([
    
    Bidirectional(
        GRU(64)
    ),
    
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ bidirectional (Bidirectional)        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)


# 🏗️ Stacked / Deep GRU

Multiple GRU layers stacked vertically.

Benefits:
✅ Hierarchical feature learning  
✅ Better representation power  

Drawback:
❌ Increased computation


In [11]:

# Stacked GRU Model

model = Sequential([
    
    GRU(
        128,
        return_sequences=True,
        input_shape=(30, 8)
    ),
    
    GRU(64),
    
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ gru_4 (GRU)                          │ (None, 30, 128)             │          52,992 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ gru_5 (GRU)                          │ (None, 64)                  │          37,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 1)                   │              65 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 90,305 (352.75 KB)

 Trainable params: 90,305 (352.75 KB)

 Non-trainable params: 0 (0.00 B)


# ⚡ Why GRU Is Faster Than LSTM

GRU is faster because:

✅ Fewer gates  
✅ No separate cell state  
✅ Fewer matrix multiplications  
✅ Lower parameter count  

Result:
- Faster training
- Lower latency
- Better efficiency



# ⚖️ When to Use GRU Instead of LSTM

Use GRU when:

✅ Faster training needed  
✅ Smaller dataset  
✅ Limited hardware  
✅ Real-time systems  
✅ Lower memory requirements  

Use LSTM when:

✅ Extremely long dependencies exist  
✅ More memory control required  


In [12]:

# 🧪 PyTorch GRU Example

import torch
import torch.nn as nn

class GRUNetwork(nn.Module):

    def __init__(self):

        super().__init__()

        self.gru = nn.GRU(
            input_size=8,
            hidden_size=64,
            batch_first=True
        )

        self.fc = nn.Linear(64, 1)

    def forward(self, x):

        output, hidden = self.gru(x)

        out = self.fc(hidden[-1])

        return out

model = GRUNetwork()

x = torch.randn(32, 30, 8)

output = model(x)

print("Output Shape:", output.shape)


Output Shape: torch.Size([32, 1])



# 🎯 Final Takeaways

GRU is:

✅ Lightweight  
✅ Computationally efficient  
✅ Strong for sequential learning  
✅ Faster than LSTM  
✅ Easier to train  

---

# 🧠 Core Intuition

Think of GRU as:

> “An intelligent memory controller for sequential data.”

It continuously decides:
- What to remember
- What to forget
- What to update

while learning patterns across time.
